#!/bin/bash
set -x

#################
## ENVIRONMENT ##
#################

run_id="delete-cstor";test_name=$(${utils_path}/generate_test_name testcase=openebs-target-failure metadata=${run_id})

###################
## DEPENDENCIES  ##
###################

${utils_path}/setup_dependencies litmus-test

## Clone the litmus repo, navigate to litmus root 
#git clone https://github.com/openebs/litmus.git
#cd litmus
git clone https://github.com/mittachaitu/litmus.git
cd litmus
git checkout change_delays_retries


######################
## JOB DEPENDENCIES ##
######################

sleep 180;
containerStateCmd="kubectl get pod -n litmus -l name=openebs-target-failure-cstor -o custom-columns=:.status.containerStatuses[].state..reason --no-headers"
while true; do
  cstate=$(eval ${containerStateCmd}); rc=$?
  if [[ $rc -eq 0 && ! -z $cstate ]]; then
    if [[ ! $cstate =~ 'Completed' ]]; then
      sleep 1
    else break;
    fi
  else
    echo "unable to get litmus container status for target kill test"; exit 1
  fi
done

############################
## LITMUS PRECONDITIONING ##
############################

: << EOF
  ----------------------------------------------------------------------------------------
 | specAttribute        | kind     | jiva                   | cStor-sparse                 |
  ---------------------------------------------------------------------------------------- |
 | litmusJobLabel       | jobSpec  | openebs-target-failure | openebs-target-delete-cstor  |
 | Chaos Type           | env      | "target-kill"          | "target-delete"              |
 | appNamespace         | env      | app-percona-ns         | percona-cstor                |
 | runID                | env(add) |    -                   | delete-cstor                 | 
  ----------------------------------------------------------------------------------------
EOF

cp apps/percona/chaos/openebs_target_failure/run_litmus_test.yml run_test.yml
sed -i -e 's/name: openebs-target-failure/name: openebs-target-delete-cstor/g' \
-e 's/value: "target-kill"/value: "target-delete"/g' \
-e 's/value: app-percona-ns/value: percona-cstor/g' run_test.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_test.yml

#################
## RUNNER MAIN ##
#################

echo "Running the litmus test.."
${utils_path}/litmus_job_runner label='name:openebs-target-delete-cstor' job=run_test.yml
${utils_path}/task_delimiter;

echo "Dumping state of cluster post job run"; echo ""
${utils_path}/dump_cluster_state;
${utils_path}/task_delimiter;

#################
## GET RESULT  ##
#################

## Check the test status & result from the litmus result custom resource
${utils_path}/get_litmus_result ${test_name}
