#!/bin/bash
set -x

time="date"
current_time=$(eval $time)
job_id=$CI_JOB_ID
pipeline_id=$CI_PIPELINE_ID
releaseTag=$RELEASE_TAG
from_version=$FROM_VERSION
to_version=$RELEASE_TAG
upgrade_imageTag=$UPGRADE_IMAGE_TAG
new_ndmTag=$NDM_TAG
deploy_type=$DEPLOY_TYPE

source ~/.profile

present_dir=$(pwd)
echo $present_dir

echo "Setting up test dependencies.."	
${utils_path}/setup_dependencies litmus-test

bash script/utils/pooling jobname:upgrade-control-plane
bash script/utils/e2e-cr jobname:upgrade-jiva jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag"

test_name=$(bash script/utils/generate_test_name testcase=openebs-upgrade metadata="")
echo $test_name

git clone https://github.com/mayadata-io/litmus.git
cd litmus
echo "Running the litmus test.."

cp providers/openebs/bulk-upgrade/run_litmus_test.yml upgrade-jiva.yml
sed -i -e '/name: UPGRADE_JIVA/{n;s/.*/            value: "true"/}' \
-e '/name: FROM_VERSION/{n;s/.*/            value: '"'$from_version'"'/}' \
-e '/name: TO_VERSION/{n;s/.*/            value: '"'$to_version'"'/}' \
-e '/name: UPGRADE_IMAGE_TAG/{n;s/.*/            value: '"'$upgrade_imageTag'"'/}' \
-e '/name: NEW_NDM_TAG/{n;s/.*/            value: '"'$new_ndmTag'"'/}' \
-e '/name: DEPLOY_TYPE/{n;s/.*/            value: '"'$deploy_type'"'/}' \
-e '/name: OPERATOR_NS/{n;s/.*/            value: openebs/}' upgrade-jiva.yml

sed -i -e 's/app: openebs-upgrade/app: openebs-jiva-upgrade/g' upgrade-jiva.yml

cat upgrade-jiva.yml

bash ../script/utils/litmus_job_runner label='app:openebs-jiva-upgrade' job=upgrade-jiva.yml

echo "Dumping state of cluster post job run"; echo ""
bash ../script/utils/dump_cluster_state;

cd ..
bash script/utils/event_updater jobname:upgrade-jiva $test_name jobid:"$job_id" pipelineid:"$pipeline_id"
#################
## GET RESULT  ##
#################
rc_val=$(echo $?)

## Check the test status & result from the litmus result custom resource
source ~/.profile
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

current_time=$(eval $time)
bash script/utils/e2e-cr jobname:upgrade-jiva jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag" test_result:$testResult

if [ "$rc_val" != "0" ]; then
exit 1;
fi
