#!/bin/bash
set -x

source ~/.profile

time="date"
current_time=$(eval $time)
job_id=$CI_JOB_ID
pipeline_id=$CI_PIPELINE_ID
releaseTag=$RELEASE_TAG
from_version=$FROM_VERSION
to_version=$RELEASE_TAG
upgrade_imageTag=$UPGRADE_IMAGE_TAG
new_ndmTag=$NDM_TAG
deploy_type=$DEPLOY_TYPE
helm_repo=$HELM_REPO
helm_branch=$HELM_BRANCH
upgrade_to_ci=$UPGRADE_TO_CI

present_dir=$(pwd)
echo $present_dir

echo "Setting up test dependencies.."	
${utils_path}/setup_dependencies litmus-test

kubectl get pods -n openebs -o yaml | grep image | grep -v imageID | grep quay

bash script/utils/e2e-cr jobname:upgrade-control-plane jobphase:Waiting
bash script/utils/e2e-cr jobname:upgrade-control-plane jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag"
bash script/utils/e2e-cr jobname:upgrade-jiva jobphase:Waiting
bash script/utils/e2e-cr jobname:upgrade-cstor jobphase:Waiting

test_name=$(bash script/utils/generate_test_name testcase=openebs-upgrade metadata="")
echo $test_name

git clone https://github.com/mayadata-io/litmus.git
cd litmus
echo "Running the litmus test.."

cp providers/openebs/bulk-upgrade/run_litmus_test.yml upgrade_control_plane.yml

sed -i -e '/name: UPGRADE_CONTROL_PLANE/{n;s/.*/            value: "true"/}' \
-e '/name: FROM_VERSION/{n;s/.*/            value: '"'$from_version'"'/}' \
-e '/name: TO_VERSION/{n;s/.*/            value: '"'$to_version'"'/}' \
-e '/name: UPGRADE_IMAGE_TAG/{n;s/.*/            value: '"'$upgrade_imageTag'"'/}' \
-e '/name: NEW_NDM_TAG/{n;s/.*/            value: '"'$new_ndmTag'"'/}' \
-e '/name: UPGARDE_TO_CI/{n;s/.*/            value: '"'$upgrade_to_ci'"'/}' \
-e '/name: DEPLOY_TYPE/{n;s/.*/            value: '"'$deploy_type'"'/}' \
-e '/name: HELM_REPO/{n;s/.*/            value: '"'$helm_repo'"'/}' \
-e '/name: HELM_BRANCH/{n;s/.*/            value: '"'$helm_branch'"'/}' \
-e '/name: OPERATOR_NS/{n;s/.*/            value: openebs/}' upgrade_control_plane.yml

cat upgrade_control_plane.yml

bash ../script/utils/litmus_job_runner label='app:openebs-upgrade' job=upgrade_control_plane.yml

echo "Dumping state of cluster post job run"; echo ""
bash ../script/utils/dump_cluster_state;

cd ..
bash script/utils/event_updater jobname:upgrade-control-plane $test_name jobid:"$job_id" pipelineid:"$pipeline_id"
#################
## GET RESULT  ##
#################
rc_val=$(echo $?)

## Check the test status & result from the litmus result custom resource
source ~/.profile
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

current_time=$(eval $time)
bash script/utils/e2e-cr jobname:upgrade-control-plane jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag" test_result:$testResult

if [ "$rc_val" != "0" ]; then
exit 1;
fi
