#!/bin/bash
set -x

#################
## ENVIRONMENT ##
#################

run_id="deprovision-cstor";test_name=$(${utils_path}/generate_test_name testcase=mongodb-deployment metadata=${run_id})

###################
## DEPENDENCIES  ##
###################

${utils_path}/setup_dependencies litmus-test

## Clone the litmus repo, navigate to litmus root 
git clone https://github.com/openebs/litmus.git
cd litmus

############################
## LITMUS PRECONDITIONING ##
############################

: << EOF
  -------------------------------------------------------------------------------------------
 | specAttribute        | kind	   | jiva        	         | cStor-sparse  	     |
  -------------------------------------------------------------------------------------------
 | litmusJobLabel       | jobSpec  | mongodb-deployment-litmus   | mongodb-deprovision-cstor |
 | Action               | env 	   | provision                   | deprovision               |
 | appNamespace         | env	   | app-mongo-ns                | mongocstor                |
 | runID		| env(add) | 	-	         	 | cstor                     |
  -------------------------------------------------------------------------------------------
EOF

cp apps/mongodb/deployers/run_litmus_test.yml run_test.yml
sed -i -e 's/app: mongodb-deployment-litmus/app: mongodb-deprovision-cstor/g' \
-e 's/value: provision/value: deprovision/g' \
-e 's/value: app-mongo-ns/value: mongocstor/g' run_test.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_test.yml

#################
## RUNNER MAIN ##
#################

echo "Running the litmus test.."
${utils_path}/litmus_job_runner label='app:mongodb-deprovision-cstor' job=run_test.yml
${utils_path}/task_delimiter;

echo "Dumping state of cluster post job run"; echo ""
${utils_path}/dump_cluster_state;
${utils_path}/task_delimiter;

#################
## GET RESULT  ##
#################

## Check the test status & result from the litmus result custom resource
${utils_path}/get_litmus_result ${test_name}
