#!/bin/bash
set -e

derive_cluster_details_infra()
{
 path=$(pwd)
 ## Get kubeconfig file into infra-setup gitlab runner pod
 mkdir .kube-openebs
 mkdir ~/.kube
 cp  .kube/config .kube-openebs/config

 ## Transfer cluster config & physical details into '.kube-openebs'
 cp  .kube/config ~/.kube/config
 cat $path/.kube/clusters > .kube-openebs/clusters
 cat $path/.kube/zone > .kube-openebs/zone
}

setup_cluster_config_test()
{
 mkdir ~/.kube
 cp .kube-openebs/config ~/.kube/config
 mkdir ~/logs
 cp .kube-openebs/clusters ~/logs
 cp .kube-openebs/zone ~/logs
 cluster_name=$(cat ~/logs/clusters)
 zone=$(cat ~/logs/zone)
 path=$(pwd)
 echo $SDK_TOKEN > key.json
 gcloud auth activate-service-account --key-file=key.json
 gcloud config set project openebs-ci
 export GOOGLE_APPLICATION_CREDENTIALS="$path/key.json"
 export GCP_SERVICE_ACCOUNT_FILE="$path/key.json"
 export GKEUSER=`echo $GKE_USER`

 gcloud container clusters get-credentials $cluster_name --zone $zone --project openebs-ci
}

if [[ $1 == "infra-setup" ]]; then
 derive_cluster_details_infra;
elif [[ $1 == "litmus-test" ]]; then
 setup_cluster_config_test;
else echo "invalid job type"; exit 1
fi
