#!/bin/bash
set -e

echo $SDK_TOKEN > key.json
gcloud auth activate-service-account --key-file=key.json
gcloud config set project openebs-ci
export GOOGLE_APPLICATION_CREDENTIALS="/openebs/e2e-gke/key.json"

# git clone https://github.com/atulabhi/litmus.git

# cd litmus/

# git checkout v0.7-RC1

git clone https://github.com/openebs/litmus.git
cd litmus/
git checkout gke-k8s

cd k8s/gke/k8s-installer/

echo "creating cluster"

ansible-playbook create-gke-cluster.yml -vv

mkdir /openebs/e2e-gke/.kube
cat ~/.kube/config > /openebs/e2e-gke/.kube/config
cat ~/.kube/config > /openebs/e2e-gke/.kube/admin.conf
cat ~/logs/clusters > /openebs/e2e-gke/.kube/clusters

kubectl get nodes
wget https://raw.githubusercontent.com/openebs/litmus/master/hack/rbac.yaml
kubectl apply -f rbac.yaml
kubectl create configmap kubeconfig --from-file=/openebs/e2e-gke/.kube/admin.conf -n litmus