#!/bin/bash
set -e

echo $SDK_TOKEN > key.json
gcloud auth activate-service-account --key-file=key.json
gcloud config set project openebs-ci
export GOOGLE_APPLICATION_CREDENTIALS="/openebs/e2e-gke/key.json"
export GCP_SERVICE_ACCOUNT_FILE="/openebs/e2e-gke/key.json"
export GKEUSER=`echo $GKE_USER`

#---------------------Runner Cleanup-----------------------------------

kubectl get po -n gitlab-runner
kubectl get pods -n gitlab-runner -o go-template --template '{{range .items}}{{.metadata.name}} {{.metadata.creationTimestamp}}{{"\n"}}{{end}}' | awk '$2 <= "'$(date -d'now-6 hours' -Ins --utc | sed 's/+0000/Z/')'" { print $1 }' | grep "runner.*project-5" | xargs --no-run-if-empty kubectl delete pod -n gitlab-runner

git clone https://github.com/openebs/litmus.git
cd litmus/k8s/gke/k8s-installer/

echo "creating cluster"

ansible-playbook create-gke-cluster.yml -vv

mkdir /openebs/e2e-gke/.kube
cat ~/.kube/config > /openebs/e2e-gke/.kube/config
cat ~/.kube/config > /openebs/e2e-gke/.kube/admin.conf
cat ~/logs/clusters > /openebs/e2e-gke/.kube/clusters
cat ~/logs/zone > /openebs/e2e-gke/.kube/zone

kubectl get nodes
wget https://raw.githubusercontent.com/openebs/litmus/master/hack/rbac.yaml
kubectl apply -f rbac.yaml
kubectl create configmap kubeconfig --from-file=/openebs/e2e-gke/.kube/admin.conf -n litmus
