#!/bin/bash
set -e
path=$(pwd)
echo $SDK_TOKEN > key.json
gcloud auth activate-service-account --key-file=key.json
gcloud config set project openebs-ci
export GOOGLE_APPLICATION_CREDENTIALS="$path/key.json"
export GCP_SERVICE_ACCOUNT_FILE="$path/key.json"
export GKEUSER=`echo $GKE_USER`

git clone https://github.com/openebs/litmus.git
cd litmus/k8s/gke/k8s-installer/

echo "creating cluster"

ansible-playbook create-gke-cluster.yml -vv

mkdir $path/.kube
cat ~/.kube/config > $path/.kube/config
cat ~/.kube/config > $path/.kube/admin.conf
cat ~/logs/clusters > $path/.kube/clusters
cat ~/logs/zone > $path/.kube/zone

kubectl get nodes
wget https://raw.githubusercontent.com/openebs/litmus/master/hack/rbac.yaml
kubectl apply -f rbac.yaml
kubectl create configmap kubeconfig --from-file=$path/.kube/admin.conf -n litmus
