#!/bin/bash
set -e

echo "Deploying statefulapps"
mkdir ~/.kube
cp .kube-openebs/config ~/.kube/config
mkdir ~/logs
cp .kube-openebs/clusters ~/logs

git clone https://github.com/atulabhi/litmus.git

cd litmus

git checkout v0.7-RC1


kubectl apply -f apps/percona/deployers/deploy_percona_litmus.yaml

litmus_pod=$(kubectl get pod -a -n litmus --no-headers -o custom-columns=:metadata.name | grep litmus-percona)
status_cmd='kubectl logs $litmus_pod -n litmus -c ansibletest'

sleep 120
while [[ $(kubectl get pod $litmus_pod --no-headers -n litmus -o custom-columns=:status.phase) =~ 'Running' ]]
do
   echo "Still Running sir..."
   sleep 1
done
if [[ ! $(eval $status_cmd) =~ 'FAILED!' ]]; then
   TestStatus='Pass'
else
  TestStatus='Fail'
fi
echo $TestStatus

echo "========================================================================="

eval $status_cmd

kubectl get po -n litmus

kubectl get sc

